#!/bin/bash

if [ "$1" = "" ]; then
    echo "usage: ./release JANET_VERSION"
    exit 1
fi
RELEASE="static/$1"
if [ -e "$RELEASE" ]; then
    rm -rf "$RELEASE"
fi
make
mkdir "$RELEASE"
echo "Moving site into static..."
cp -r site/* "$RELEASE"
echo "Removing nested extra releases..."
rm -rf "$RELEASE"/?.?.?

